package com.zg.sanctuary.core

import androidx.compose.ui.graphics.Color

val HINT_COLOR: Color = Color(0xFF6B7582)
val DIVIDER_COLOR : Color = Color(0x996B7582)
val NORMAL_LABEL_COLOR: Color = Color(0xFF6B7582)
val TEXT_FIELD_BACKGROUND_COLOR = Color(0xFFF2F2F5)
val PRIMARY_COLOR: Color = Color(0xFFDBE8F2)
val ACCENT_COLOR: Color = Color(0xFFF2F2F5)
val CHIP_COLOR : Color = Color(0xFFF0F2F5)
val POST_BUTTON_COLOR = Color(0xFF0A80ED)

val CONVERSATION_MESSAGE_COLOR = Color(0xFF61758A)

val DISABLED_BUTTON_COLOR = Color(0xFFF2F2F5)

val MESSAGE_BUBBLE_COLOR = Color(0xFF0A80ED)
val MESSAGE_BUBBLE_COLOR_RECEIVER = Color(0xFFF0F2F5)